- .travis.yml
- package-lock.json
- src/model/database/db_build_test.sql
- src/model/database/db_connection.js
- Add travis file which adds a postgres database  
- Check for travis environment variable to switch over the database created by travis in before_script
> Travis setup

- package-lock.json
- package.json
- public/css/style.css
- public/index.html
- src/app.js
- src/controller/index.js
- src/model/database/db_build.sql
- src/model/database/db_build_test.sql
- src/test/app.test.js
> add home and static routes, add basic homepage

- package-lock.json
- package.json
- src/app.js
- src/controllers/home.js
- src/controllers/index.js
- src/views/home.hbs
- src/views/layouts/main.hbs
> set up handlebars and modularise home route

- .eslintrc.json
- src/controllers/home.js
- src/model/database/db_connection.js
Discovered [here](https://eslint.org/docs/user-guide/configuring#configuring-rules) how to turn off rule in eslint
> turn off no-console rule in eslint and apply linting

- src/model/queries/getMemberData.js
- src/test/db.test.js
The query will select a member from the database based on their `github_id`
Closes #43
> query to get member data from database [WIP]

- package.json
- src/app.js
- src/controllers/error.js
- src/controllers/index.js
- src/oauth.js
relates #48
closes #27 
closes #31 
This PR adds verification that a new signup is a member of FAC and some basic server error handling (not complete)
oAuth.js requires testing, but not sure how to do this with an IFFE function. 
Pull request is for review only - best to pull in other master changes to controller index before merging.
> Verification of FAC github org membership

- package-lock.json
- src/controllers/home.js
- src/views/layouts/main.hbs
- src/views/partials/footer.hbs
- src/views/partials/header.hbs
- src/views/partials/htmlHead.hbs
closes #16 
closes #40 
closes #41 
The html head, header and footer is split up into partials
The header partials checks if a member is logged in and displays a logout button
> Logout btn

- src/controllers/error.js
- src/test/app.test.js
- src/views/error.hbs
> add error handling

- public/css/style.css
- src/views/partials/header.hbs
- src/views/profileDetails.hbs
Closes #71 Relates #44 Relates #40
> added hbs autopopulation, fixed logout button hbs conditional

- src/oauth.js
> fix if/else branching in oauth checkOrgMembership function

- src/test/app.test.js
- src/test/db.test.js
I updated the Test Tape is working test name to clarify which are the APP/ROUTER tests vs. the DB/QUERY tests when running all of them. .  We should perhaps modularise test files further.
> update test names in test.js files for clarity when running tests

- .gitignore
- public/css/style.css
- public/css/style.scss
- src/views/home.hbs
- src/views/partials/footer.hbs
- src/views/partials/header.hbs
- src/views/partials/htmlHead.hbs
- src/views/partials/profile_jobDetails.hbs
- src/views/partials/profile_myDetails.hbs
- src/views/partials/profile_viewMode.hbs
> Add basic css styling based on style guide

- src/controllers/error.js
- src/controllers/index.js
- src/controllers/middleware.js
- src/controllers/profile.js
- src/model/queries/getAllMemberData.js
- src/model/queries/postMemberInfo.js
- src/oauth.js
- src/test/app.test.js
- src/test/db.test.js
- src/views/partials/profile_jobDetails.hbs
- src/views/partials/profile_viewMode.hbs
> Error handling + moving saveJobDetails to profile.js handler

- Design Folder/journey.md
> Add documentation on the design process (week one)

- package-lock.json
- package.json
- src/lib/getGitHubStack.js
- src/test/api.test.js
- src/test/unit.test.js
relates to #127
- adds standalone function getGitHubRepoLanguages 
- takes in access token and github_handle
- returns an array of strings of the user's repo language. 
This still needs to be integrated with the codebase.  I think we will need to run this into auth.js where we have access to the users accessToken
> 127 api tech stack pull

- src/controllers/profile.js
- src/views/allmembers.hbs
- src/views/partials/profile_jobDetails.hbs
- src/views/partials/profile_viewMode.hbs
> created card links and conditional display of edit btns/privacy info

- src/lib/githubApiCalls.js
- src/oauth.js
- src/test/api.test.js
- src/test/unit.test.js
relates to #27
gets the users tech stack based on their github repos. 
Needs to be posted to the DB.
> issue127 autosuggest stack 

- package-lock.json
- package.json
- src/app.js
- adds helmet security module
- disables 'x-powered-by' headers
- changes cookie session name. 
on the staging branch I will add the following to cookieSession: 
`secure: true,
httpOnly: true`
> security helmet added

- public/dom/index.js
- public/dom/profile.js
- src/controllers/index.js
- src/controllers/profile.js
- src/views/partials/profile_delete.hbs
Submitting delete account modal sends a delete request to `/deleteAccount`
Then changes window location `/goodbye`
> delete account endpoint

- src/lib/githubApiCalls.js
- src/test/api.test.js
remove nulls from repo languages
>  bug fix closes #142

- src/app.js
- src/oauth.js
- src/test/api.test.js
- src/test/app.test.js
- src/test/db.test.js
Uncomments potential offending tests and code causing us to hit the API Rate Limit
> remove possible api rate limit causes
